version: "3.9"
services:
  mongo-prod:
    image: mongo:6.0.4-jammy
    ports:
      - 27017:27017
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-prod
    volumes:
      - mongo-prod:/data/db
    networks:
      - backend
    command: [ "--replSet", "rs0", "--bind_ip_all" ]

  mongo-test:
    image: mongo:6.0.4-jammy
    ports:
      - 27018:27017
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-test
    volumes:
      -  mongo-test:/data/db
    networks:
      - backend
    command: [ "--replSet", "rs0", "--bind_ip_all" ]

  mongo-express-prod:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-prod:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - backend

  mongo-express-test:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-test:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
    - backend

networks:
  backend:

volumes:
  mongo-prod:
  mongo-test:
